# Tokenizer config placeholder
# configs/tokenizer_config.yaml

tokenizer_class: LlamaTokenizer
clean_up_tokenization_spaces: true
model_max_length: 2048
padding_side: right
truncation_side: right
use_fast: true
add_prefix_space: true
special_tokens_map_file: null